language: php

php:
#  - 7.0
#  - 7.1
#  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  - composer install --prefer-dist

script:
  - composer test:cov

after_success:
  - bash <(curl -s https://codecov.io/bash)
